# Generated by cpp11: do not edit by hand

ols_mat_ <- function(y, x) {
  .Call(`_cpp11armadillotest_ols_mat_`, y, x)
}

ols_dbl_ <- function(y, x) {
  .Call(`_cpp11armadillotest_ols_dbl_`, y, x)
}

eigen_sym_mat_ <- function(x) {
  .Call(`_cpp11armadillotest_eigen_sym_mat_`, x)
}

eigen_sym_dbl_ <- function(x) {
  .Call(`_cpp11armadillotest_eigen_sym_dbl_`, x)
}

eigen_gen_mat_ <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_mat_`, x)
}

eigen_gen_mat_complex_wrapper_ <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_mat_complex_wrapper_`, x)
}

eigen_gen_dbl_complex_wrapper_ <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_dbl_complex_wrapper_`, x)
}

eigen_gen_no_wrapper_ <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_no_wrapper_`, x)
}

chol_mat_ <- function(x, type) {
  .Call(`_cpp11armadillotest_chol_mat_`, x, type)
}

ols_qr_mat_ <- function(y, x, econ) {
  .Call(`_cpp11armadillotest_ols_qr_mat_`, y, x, econ)
}

ols_qr_dbl_ <- function(y, x, econ) {
  .Call(`_cpp11armadillotest_ols_qr_dbl_`, y, x, econ)
}

capm_ <- function(r, m, f) {
  .Call(`_cpp11armadillotest_capm_`, r, m, f)
}

typedef_Col_double_ <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Col_double_`, x)
}

typedef_Col_int_ <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Col_int_`, x)
}

typedef_uvec_ <- function(x) {
  .Call(`_cpp11armadillotest_typedef_uvec_`, x)
}

typedef_Mat_double_ <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Mat_double_`, x)
}

typedef_Mat_int_ <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Mat_int_`, x)
}

typedef_SpMat_double_ <- function(x) {
  .Call(`_cpp11armadillotest_typedef_SpMat_double_`, x)
}

typedef_SpMat_int_ <- function(x) {
  .Call(`_cpp11armadillotest_typedef_SpMat_int_`, x)
}
