# Generated by cpp11: do not edit by hand

ols_mat <- function(y, x) {
  .Call(`_cpp11armadillotest_ols_mat`, y, x)
}

ols_dbl <- function(y, x) {
  .Call(`_cpp11armadillotest_ols_dbl`, y, x)
}

eigen_sym_mat <- function(x) {
  .Call(`_cpp11armadillotest_eigen_sym_mat`, x)
}

eigen_sym_dbl <- function(x) {
  .Call(`_cpp11armadillotest_eigen_sym_dbl`, x)
}

eigen_gen_mat <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_mat`, x)
}

eigen_gen_mat_complex_wrapper <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_mat_complex_wrapper`, x)
}

eigen_gen_dbl_complex_wrapper <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_dbl_complex_wrapper`, x)
}

eigen_gen_no_wrapper <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_no_wrapper`, x)
}

chol_mat <- function(x, type) {
  .Call(`_cpp11armadillotest_chol_mat`, x, type)
}

ols_qr_mat <- function(y, x, econ) {
  .Call(`_cpp11armadillotest_ols_qr_mat`, y, x, econ)
}

ols_qr_dbl <- function(y, x, econ) {
  .Call(`_cpp11armadillotest_ols_qr_dbl`, y, x, econ)
}

capm <- function(r, m, f) {
  .Call(`_cpp11armadillotest_capm`, r, m, f)
}

typedef_Col_double <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Col_double`, x)
}

typedef_Col_int <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Col_int`, x)
}

typedef_uvec <- function(x) {
  .Call(`_cpp11armadillotest_typedef_uvec`, x)
}

typedef_Mat_double <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Mat_double`, x)
}

typedef_Mat_int <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Mat_int`, x)
}

typedef_SpMat_double <- function(x) {
  .Call(`_cpp11armadillotest_typedef_SpMat_double`, x)
}

typedef_SpMat_int <- function(x) {
  .Call(`_cpp11armadillotest_typedef_SpMat_int`, x)
}

typedef_dblmat_exchangeability <- function(x) {
  .Call(`_cpp11armadillotest_typedef_dblmat_exchangeability`, x)
}

typedef_spmat_exchangeability <- function(x) {
  .Call(`_cpp11armadillotest_typedef_spmat_exchangeability`, x)
}

typedef_spmat_int_exchangeability <- function(x) {
  .Call(`_cpp11armadillotest_typedef_spmat_int_exchangeability`, x)
}

random_matrix_nxn <- function(n) {
  .Call(`_cpp11armadillotest_random_matrix_nxn`, n)
}

matrix1_ <- function(a) {
  .Call(`_cpp11armadillotest_matrix1_`, a)
}

matrix2_ <- function(a) {
  .Call(`_cpp11armadillotest_matrix2_`, a)
}

column1_ <- function(x, y) {
  .Call(`_cpp11armadillotest_column1_`, x, y)
}

row1_ <- function(x, y) {
  .Call(`_cpp11armadillotest_row1_`, x, y)
}

cube1_ <- function(a, b) {
  .Call(`_cpp11armadillotest_cube1_`, a, b)
}

field1_ <- function(a, b) {
  .Call(`_cpp11armadillotest_field1_`, a, b)
}

attr1_ <- function(a) {
  .Call(`_cpp11armadillotest_attr1_`, a)
}

access1_ <- function(a) {
  .Call(`_cpp11armadillotest_access1_`, a)
}

initialization1_ <- function(a) {
  .Call(`_cpp11armadillotest_initialization1_`, a)
}

zeros1_ <- function(a) {
  .Call(`_cpp11armadillotest_zeros1_`, a)
}

ones1_ <- function(a) {
  .Call(`_cpp11armadillotest_ones1_`, a)
}

eye1_ <- function(a) {
  .Call(`_cpp11armadillotest_eye1_`, a)
}

randu1_ <- function(a) {
  .Call(`_cpp11armadillotest_randu1_`, a)
}

randn1_ <- function(a) {
  .Call(`_cpp11armadillotest_randn1_`, a)
}

randu2_ <- function(n) {
  .Call(`_cpp11armadillotest_randu2_`, n)
}

randn2_ <- function(n) {
  .Call(`_cpp11armadillotest_randn2_`, n)
}

fill1_ <- function(a) {
  .Call(`_cpp11armadillotest_fill1_`, a)
}

imbue1_ <- function(a) {
  .Call(`_cpp11armadillotest_imbue1_`, a)
}

imbue2_ <- function(a) {
  .Call(`_cpp11armadillotest_imbue2_`, a)
}

clean1_ <- function(n) {
  .Call(`_cpp11armadillotest_clean1_`, n)
}

replace1_ <- function(n) {
  .Call(`_cpp11armadillotest_replace1_`, n)
}

clamp1_ <- function(n) {
  .Call(`_cpp11armadillotest_clamp1_`, n)
}

transform1_ <- function(n) {
  .Call(`_cpp11armadillotest_transform1_`, n)
}

for_each1_ <- function(n) {
  .Call(`_cpp11armadillotest_for_each1_`, n)
}

set_size1_ <- function(n) {
  .Call(`_cpp11armadillotest_set_size1_`, n)
}

reshape1_ <- function(n) {
  .Call(`_cpp11armadillotest_reshape1_`, n)
}

resize1_ <- function(n) {
  .Call(`_cpp11armadillotest_resize1_`, n)
}

copy_size1_ <- function(n) {
  .Call(`_cpp11armadillotest_copy_size1_`, n)
}

reset1_ <- function(n) {
  .Call(`_cpp11armadillotest_reset1_`, n)
}

subview1_ <- function(n) {
  .Call(`_cpp11armadillotest_subview1_`, n)
}

subview2_ <- function(n) {
  .Call(`_cpp11armadillotest_subview2_`, n)
}

diagonal1_ <- function(n) {
  .Call(`_cpp11armadillotest_diagonal1_`, n)
}

each_col1_ <- function(n) {
  .Call(`_cpp11armadillotest_each_col1_`, n)
}

each_row1_ <- function(n) {
  .Call(`_cpp11armadillotest_each_row1_`, n)
}

each_slice1_ <- function(n) {
  .Call(`_cpp11armadillotest_each_slice1_`, n)
}

set_real1_ <- function(n) {
  .Call(`_cpp11armadillotest_set_real1_`, n)
}

set_real2_ <- function(n) {
  .Call(`_cpp11armadillotest_set_real2_`, n)
}

set_imag1_ <- function(n) {
  .Call(`_cpp11armadillotest_set_imag1_`, n)
}

insert_columns1_ <- function(n) {
  .Call(`_cpp11armadillotest_insert_columns1_`, n)
}

insert_rows1_ <- function(n) {
  .Call(`_cpp11armadillotest_insert_rows1_`, n)
}

insert_slices1_ <- function(n) {
  .Call(`_cpp11armadillotest_insert_slices1_`, n)
}

shed_columns1_ <- function(n) {
  .Call(`_cpp11armadillotest_shed_columns1_`, n)
}

shed_rows1_ <- function(n) {
  .Call(`_cpp11armadillotest_shed_rows1_`, n)
}

shed_slices1_ <- function(n) {
  .Call(`_cpp11armadillotest_shed_slices1_`, n)
}

swap_columns1_ <- function(n) {
  .Call(`_cpp11armadillotest_swap_columns1_`, n)
}

swap_rows1_ <- function(n) {
  .Call(`_cpp11armadillotest_swap_rows1_`, n)
}

swap1_ <- function(n) {
  .Call(`_cpp11armadillotest_swap1_`, n)
}

memptr1_ <- function(n) {
  .Call(`_cpp11armadillotest_memptr1_`, n)
}

colptr1_ <- function(n) {
  .Call(`_cpp11armadillotest_colptr1_`, n)
}

iterators1_ <- function(n) {
  .Call(`_cpp11armadillotest_iterators1_`, n)
}

iterators2_ <- function(n) {
  .Call(`_cpp11armadillotest_iterators2_`, n)
}

iterators3_ <- function(n) {
  .Call(`_cpp11armadillotest_iterators3_`, n)
}

iterators4_ <- function(n) {
  .Call(`_cpp11armadillotest_iterators4_`, n)
}

compatibility1_ <- function(n) {
  .Call(`_cpp11armadillotest_compatibility1_`, n)
}

compatibility2_ <- function(n) {
  .Call(`_cpp11armadillotest_compatibility2_`, n)
}

as_col1_ <- function(n) {
  .Call(`_cpp11armadillotest_as_col1_`, n)
}

as_row1_ <- function(n) {
  .Call(`_cpp11armadillotest_as_row1_`, n)
}

col_as_mat1_ <- function(n) {
  .Call(`_cpp11armadillotest_col_as_mat1_`, n)
}

row_as_mat1_ <- function(n) {
  .Call(`_cpp11armadillotest_row_as_mat1_`, n)
}

as_dense1_ <- function(n) {
  .Call(`_cpp11armadillotest_as_dense1_`, n)
}

transpose1_ <- function(n) {
  .Call(`_cpp11armadillotest_transpose1_`, n)
}

transpose2_ <- function(n) {
  .Call(`_cpp11armadillotest_transpose2_`, n)
}

inverse1_ <- function(a, b) {
  .Call(`_cpp11armadillotest_inverse1_`, a, b)
}

maxmin1_ <- function(n) {
  .Call(`_cpp11armadillotest_maxmin1_`, n)
}

index_maxmin1_ <- function(n) {
  .Call(`_cpp11armadillotest_index_maxmin1_`, n)
}

in_range1_ <- function(n) {
  .Call(`_cpp11armadillotest_in_range1_`, n)
}

is_empty1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_empty1_`, n)
}

is_vec1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_vec1_`, n)
}

is_sorted1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_sorted1_`, n)
}

is_triangular1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_triangular1_`, n)
}

is_diagonal1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_diagonal1_`, n)
}

is_square1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_square1_`, n)
}

is_symmetric1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_symmetric1_`, n)
}

is_hermitian1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_hermitian1_`, n)
}

is_sympd1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_sympd1_`, n)
}

is_zero1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_zero1_`, n)
}

is_finite1_ <- function(n) {
  .Call(`_cpp11armadillotest_is_finite1_`, n)
}

has_inf1_ <- function(n) {
  .Call(`_cpp11armadillotest_has_inf1_`, n)
}

has_nan1_ <- function(n) {
  .Call(`_cpp11armadillotest_has_nan1_`, n)
}

linspace1_ <- function(n) {
  .Call(`_cpp11armadillotest_linspace1_`, n)
}

logspace1_ <- function(n) {
  .Call(`_cpp11armadillotest_logspace1_`, n)
}

regspace1_ <- function(delta) {
  .Call(`_cpp11armadillotest_regspace1_`, delta)
}

randperm1_ <- function(n, m) {
  .Call(`_cpp11armadillotest_randperm1_`, n, m)
}

eye2_ <- function(n) {
  .Call(`_cpp11armadillotest_eye2_`, n)
}

ones2_ <- function(n) {
  .Call(`_cpp11armadillotest_ones2_`, n)
}

zeros2_ <- function(n) {
  .Call(`_cpp11armadillotest_zeros2_`, n)
}

randu3_ <- function(n) {
  .Call(`_cpp11armadillotest_randu3_`, n)
}

randn3_ <- function(n) {
  .Call(`_cpp11armadillotest_randn3_`, n)
}

randg3_ <- function(n) {
  .Call(`_cpp11armadillotest_randg3_`, n)
}

speye1_ <- function(n) {
  .Call(`_cpp11armadillotest_speye1_`, n)
}

spones1_ <- function(n) {
  .Call(`_cpp11armadillotest_spones1_`, n)
}

sprandu1_ <- function(n) {
  .Call(`_cpp11armadillotest_sprandu1_`, n)
}

sprandn1_ <- function(n) {
  .Call(`_cpp11armadillotest_sprandn1_`, n)
}

toeplitz1_ <- function(n) {
  .Call(`_cpp11armadillotest_toeplitz1_`, n)
}

abs1_ <- function(n) {
  .Call(`_cpp11armadillotest_abs1_`, n)
}

accu1_ <- function(n) {
  .Call(`_cpp11armadillotest_accu1_`, n)
}

affmul1_ <- function(n) {
  .Call(`_cpp11armadillotest_affmul1_`, n)
}

all1_ <- function(n) {
  .Call(`_cpp11armadillotest_all1_`, n)
}

any1_ <- function(n) {
  .Call(`_cpp11armadillotest_any1_`, n)
}

approx_equal1_ <- function(n) {
  .Call(`_cpp11armadillotest_approx_equal1_`, n)
}

arg1_ <- function(n) {
  .Call(`_cpp11armadillotest_arg1_`, n)
}

as_scalar1_ <- function(n) {
  .Call(`_cpp11armadillotest_as_scalar1_`, n)
}

clamp2_ <- function(n) {
  .Call(`_cpp11armadillotest_clamp2_`, n)
}

cond1_ <- function(n) {
  .Call(`_cpp11armadillotest_cond1_`, n)
}

conj1_ <- function(n) {
  .Call(`_cpp11armadillotest_conj1_`, n)
}

conv_to1_ <- function(n) {
  .Call(`_cpp11armadillotest_conv_to1_`, n)
}

cross1_ <- function(n) {
  .Call(`_cpp11armadillotest_cross1_`, n)
}

cumsum1_ <- function(n) {
  .Call(`_cpp11armadillotest_cumsum1_`, n)
}

cumprod1_ <- function(n) {
  .Call(`_cpp11armadillotest_cumprod1_`, n)
}

det1_ <- function(n) {
  .Call(`_cpp11armadillotest_det1_`, n)
}

diagmat1_ <- function(n) {
  .Call(`_cpp11armadillotest_diagmat1_`, n)
}

diagvec1_ <- function(n) {
  .Call(`_cpp11armadillotest_diagvec1_`, n)
}

diags1_ <- function(n) {
  .Call(`_cpp11armadillotest_diags1_`, n)
}

spdiags1_ <- function(n) {
  .Call(`_cpp11armadillotest_spdiags1_`, n)
}

diff1_ <- function(n) {
  .Call(`_cpp11armadillotest_diff1_`, n)
}

dot1_ <- function(n) {
  .Call(`_cpp11armadillotest_dot1_`, n)
}

eps1_ <- function(n) {
  .Call(`_cpp11armadillotest_eps1_`, n)
}

expmat1_ <- function(n) {
  .Call(`_cpp11armadillotest_expmat1_`, n)
}

expmat_sym1_ <- function(n) {
  .Call(`_cpp11armadillotest_expmat_sym1_`, n)
}

find1_ <- function(n) {
  .Call(`_cpp11armadillotest_find1_`, n)
}

find_finite1_ <- function(n) {
  .Call(`_cpp11armadillotest_find_finite1_`, n)
}

find_nonfinite1_ <- function(n) {
  .Call(`_cpp11armadillotest_find_nonfinite1_`, n)
}

find_nan1_ <- function(n) {
  .Call(`_cpp11armadillotest_find_nan1_`, n)
}

find_unique1_ <- function(n) {
  .Call(`_cpp11armadillotest_find_unique1_`, n)
}

flip1_ <- function(n) {
  .Call(`_cpp11armadillotest_flip1_`, n)
}

imag1_ <- function(n) {
  .Call(`_cpp11armadillotest_imag1_`, n)
}

ind2sub1_ <- function(n) {
  .Call(`_cpp11armadillotest_ind2sub1_`, n)
}

index_min1_ <- function(n) {
  .Call(`_cpp11armadillotest_index_min1_`, n)
}

inplace_trans1_ <- function(n) {
  .Call(`_cpp11armadillotest_inplace_trans1_`, n)
}

inplace_strans1_ <- function(n) {
  .Call(`_cpp11armadillotest_inplace_strans1_`, n)
}

intersect1_ <- function(n) {
  .Call(`_cpp11armadillotest_intersect1_`, n)
}

join_rows1_ <- function(n) {
  .Call(`_cpp11armadillotest_join_rows1_`, n)
}

join_cubes1_ <- function(n) {
  .Call(`_cpp11armadillotest_join_cubes1_`, n)
}

kron1_ <- function(n) {
  .Call(`_cpp11armadillotest_kron1_`, n)
}

log_det1_ <- function(n) {
  .Call(`_cpp11armadillotest_log_det1_`, n)
}

log_det_sympd1_ <- function(n) {
  .Call(`_cpp11armadillotest_log_det_sympd1_`, n)
}

logmat1_ <- function(n) {
  .Call(`_cpp11armadillotest_logmat1_`, n)
}

logmat_sympd1_ <- function(n) {
  .Call(`_cpp11armadillotest_logmat_sympd1_`, n)
}

max1_ <- function(n) {
  .Call(`_cpp11armadillotest_max1_`, n)
}

nonzeros1_ <- function(n) {
  .Call(`_cpp11armadillotest_nonzeros1_`, n)
}

norm1_ <- function(n) {
  .Call(`_cpp11armadillotest_norm1_`, n)
}

norm2est1_ <- function(n) {
  .Call(`_cpp11armadillotest_norm2est1_`, n)
}

normalise1_ <- function(n) {
  .Call(`_cpp11armadillotest_normalise1_`, n)
}

pow1_ <- function(n) {
  .Call(`_cpp11armadillotest_pow1_`, n)
}

powmat1_ <- function(n) {
  .Call(`_cpp11armadillotest_powmat1_`, n)
}

prod1_ <- function(n) {
  .Call(`_cpp11armadillotest_prod1_`, n)
}

rank1_ <- function(n) {
  .Call(`_cpp11armadillotest_rank1_`, n)
}

rcond1_ <- function(n) {
  .Call(`_cpp11armadillotest_rcond1_`, n)
}

repelem1_ <- function(n) {
  .Call(`_cpp11armadillotest_repelem1_`, n)
}

repmat1_ <- function(n) {
  .Call(`_cpp11armadillotest_repmat1_`, n)
}

reshape2_ <- function(n) {
  .Call(`_cpp11armadillotest_reshape2_`, n)
}

resize2_ <- function(n) {
  .Call(`_cpp11armadillotest_resize2_`, n)
}

reverse1_ <- function(n) {
  .Call(`_cpp11armadillotest_reverse1_`, n)
}

roots1_ <- function(n) {
  .Call(`_cpp11armadillotest_roots1_`, n)
}

shift1_ <- function(n) {
  .Call(`_cpp11armadillotest_shift1_`, n)
}

shuffle1_ <- function(n) {
  .Call(`_cpp11armadillotest_shuffle1_`, n)
}

size1_ <- function(n) {
  .Call(`_cpp11armadillotest_size1_`, n)
}

sort1_ <- function(n) {
  .Call(`_cpp11armadillotest_sort1_`, n)
}

sort_index1_ <- function(n) {
  .Call(`_cpp11armadillotest_sort_index1_`, n)
}

sqrtmat1_ <- function(n) {
  .Call(`_cpp11armadillotest_sqrtmat1_`, n)
}

sqrtmat_sympd1_ <- function(n) {
  .Call(`_cpp11armadillotest_sqrtmat_sympd1_`, n)
}

sum1_ <- function(n) {
  .Call(`_cpp11armadillotest_sum1_`, n)
}

sum2_ <- function(n) {
  .Call(`_cpp11armadillotest_sum2_`, n)
}

sub2ind1_ <- function(n) {
  .Call(`_cpp11armadillotest_sub2ind1_`, n)
}

symmatu1_ <- function(n) {
  .Call(`_cpp11armadillotest_symmatu1_`, n)
}

trace1_ <- function(n) {
  .Call(`_cpp11armadillotest_trace1_`, n)
}

trans1_ <- function(n) {
  .Call(`_cpp11armadillotest_trans1_`, n)
}

trapz1_ <- function(n) {
  .Call(`_cpp11armadillotest_trapz1_`, n)
}

trimatu1_ <- function(n) {
  .Call(`_cpp11armadillotest_trimatu1_`, n)
}

trimatu_ind1_ <- function(n) {
  .Call(`_cpp11armadillotest_trimatu_ind1_`, n)
}

unique1_ <- function(n) {
  .Call(`_cpp11armadillotest_unique1_`, n)
}

vecnorm1_ <- function(n) {
  .Call(`_cpp11armadillotest_vecnorm1_`, n)
}

vectorise1_ <- function(n) {
  .Call(`_cpp11armadillotest_vectorise1_`, n)
}

misc1_ <- function(n) {
  .Call(`_cpp11armadillotest_misc1_`, n)
}

trig1_ <- function(n) {
  .Call(`_cpp11armadillotest_trig1_`, n)
}

mean1_ <- function(X, Y) {
  .Call(`_cpp11armadillotest_mean1_`, X, Y)
}

median1_ <- function(X, Y) {
  .Call(`_cpp11armadillotest_median1_`, X, Y)
}

stddev1_ <- function(X, Y) {
  .Call(`_cpp11armadillotest_stddev1_`, X, Y)
}

var1_ <- function(X, Y) {
  .Call(`_cpp11armadillotest_var1_`, X, Y)
}

range1_ <- function(X, Y) {
  .Call(`_cpp11armadillotest_range1_`, X, Y)
}

cov1_ <- function(X, Y) {
  .Call(`_cpp11armadillotest_cov1_`, X, Y)
}

cor1_ <- function(X, Y) {
  .Call(`_cpp11armadillotest_cor1_`, X, Y)
}

hist1_ <- function(n) {
  .Call(`_cpp11armadillotest_hist1_`, n)
}

histc1_ <- function(n) {
  .Call(`_cpp11armadillotest_histc1_`, n)
}

quantile1_ <- function(n) {
  .Call(`_cpp11armadillotest_quantile1_`, n)
}

normpdf1_ <- function(n) {
  .Call(`_cpp11armadillotest_normpdf1_`, n)
}

lognormpdf1_ <- function(n) {
  .Call(`_cpp11armadillotest_lognormpdf1_`, n)
}

normcdf1_ <- function(n) {
  .Call(`_cpp11armadillotest_normcdf1_`, n)
}

mvnrnd1_ <- function(n, m) {
  .Call(`_cpp11armadillotest_mvnrnd1_`, n, m)
}

chi2rnd1_ <- function(n, m) {
  .Call(`_cpp11armadillotest_chi2rnd1_`, n, m)
}

wishrnd1_ <- function(n) {
  .Call(`_cpp11armadillotest_wishrnd1_`, n)
}

iwishrnd1_ <- function(n, d) {
  .Call(`_cpp11armadillotest_iwishrnd1_`, n, d)
}

kmeans1_ <- function(n, d) {
  .Call(`_cpp11armadillotest_kmeans1_`, n, d)
}

gmm1_ <- function(n, d) {
  .Call(`_cpp11armadillotest_gmm1_`, n, d)
}

saveload1_ <- function(n) {
  .Call(`_cpp11armadillotest_saveload1_`, n)
}

saveload2_ <- function(n, m) {
  .Call(`_cpp11armadillotest_saveload2_`, n, m)
}

conv1_ <- function(x, y) {
  .Call(`_cpp11armadillotest_conv1_`, x, y)
}

conv2_ <- function(x, y) {
  .Call(`_cpp11armadillotest_conv2_`, x, y)
}

interp1_ <- function(n) {
  .Call(`_cpp11armadillotest_interp1_`, n)
}

interp2_ <- function(n) {
  .Call(`_cpp11armadillotest_interp2_`, n)
}

fft1_ <- function(x) {
  .Call(`_cpp11armadillotest_fft1_`, x)
}

fft2_ <- function(x) {
  .Call(`_cpp11armadillotest_fft2_`, x)
}

polyfit1_ <- function(n, m) {
  .Call(`_cpp11armadillotest_polyfit1_`, n, m)
}

polyval1_ <- function(n, m) {
  .Call(`_cpp11armadillotest_polyval1_`, n, m)
}

chol1_ <- function(x, layout, output) {
  .Call(`_cpp11armadillotest_chol1_`, x, layout, output)
}

eig_sym1_ <- function(x, method) {
  .Call(`_cpp11armadillotest_eig_sym1_`, x, method)
}

eig_gen1_ <- function(x, balance) {
  .Call(`_cpp11armadillotest_eig_gen1_`, x, balance)
}

eig_pair1_ <- function(a, b) {
  .Call(`_cpp11armadillotest_eig_pair1_`, a, b)
}

hess1_ <- function(x) {
  .Call(`_cpp11armadillotest_hess1_`, x)
}

inv1_ <- function(a) {
  .Call(`_cpp11armadillotest_inv1_`, a)
}

inv_sympd1_ <- function(a) {
  .Call(`_cpp11armadillotest_inv_sympd1_`, a)
}

lu1_ <- function(x) {
  .Call(`_cpp11armadillotest_lu1_`, x)
}

null1_ <- function(a) {
  .Call(`_cpp11armadillotest_null1_`, a)
}

orth1_ <- function(a) {
  .Call(`_cpp11armadillotest_orth1_`, a)
}

pinv1_ <- function(a) {
  .Call(`_cpp11armadillotest_pinv1_`, a)
}

qr1_ <- function(x) {
  .Call(`_cpp11armadillotest_qr1_`, x)
}

qr_econ1_ <- function(x) {
  .Call(`_cpp11armadillotest_qr_econ1_`, x)
}

qz1_ <- function(a, b, select) {
  .Call(`_cpp11armadillotest_qz1_`, a, b, select)
}

schur1_ <- function(x) {
  .Call(`_cpp11armadillotest_schur1_`, x)
}

solve1_ <- function(a, b) {
  .Call(`_cpp11armadillotest_solve1_`, a, b)
}

svd1_ <- function(x) {
  .Call(`_cpp11armadillotest_svd1_`, x)
}

svd_econ1_ <- function(x) {
  .Call(`_cpp11armadillotest_svd_econ1_`, x)
}

syl1_ <- function(a, b, c) {
  .Call(`_cpp11armadillotest_syl1_`, a, b, c)
}

eig_sym2_ <- function(x, method, k) {
  .Call(`_cpp11armadillotest_eig_sym2_`, x, method, k)
}

eig_gen2_ <- function(x, method, k) {
  .Call(`_cpp11armadillotest_eig_gen2_`, x, method, k)
}

svds1_ <- function(x, k) {
  .Call(`_cpp11armadillotest_svds1_`, x, k)
}

spsolve1_ <- function(a, b, method) {
  .Call(`_cpp11armadillotest_spsolve1_`, a, b, method)
}

ols_ <- function(x, y) {
  .Call(`_cpp11armadillotest_ols_`, x, y)
}

poisson_ <- function(x, y) {
  .Call(`_cpp11armadillotest_poisson_`, x, y)
}

test_dgCMatrix_to_SpMat <- function(x) {
  .Call(`_cpp11armadillotest_test_dgCMatrix_to_SpMat`, x)
}
