# Generated by cpp11: do not edit by hand

ols_mat <- function(y, x) {
  .Call(`_cpp11armadillotest_ols_mat`, y, x)
}

ols_dbl <- function(y, x) {
  .Call(`_cpp11armadillotest_ols_dbl`, y, x)
}

eigen_sym_mat <- function(x) {
  .Call(`_cpp11armadillotest_eigen_sym_mat`, x)
}

eigen_sym_dbl <- function(x) {
  .Call(`_cpp11armadillotest_eigen_sym_dbl`, x)
}

eigen_gen_mat <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_mat`, x)
}

eigen_gen_mat_complex_wrapper <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_mat_complex_wrapper`, x)
}

eigen_gen_dbl_complex_wrapper <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_dbl_complex_wrapper`, x)
}

eigen_gen_no_wrapper <- function(x) {
  .Call(`_cpp11armadillotest_eigen_gen_no_wrapper`, x)
}

chol_mat <- function(x, type) {
  .Call(`_cpp11armadillotest_chol_mat`, x, type)
}

ols_qr_mat <- function(y, x, econ) {
  .Call(`_cpp11armadillotest_ols_qr_mat`, y, x, econ)
}

ols_qr_dbl <- function(y, x, econ) {
  .Call(`_cpp11armadillotest_ols_qr_dbl`, y, x, econ)
}

capm <- function(r, m, f) {
  .Call(`_cpp11armadillotest_capm`, r, m, f)
}

typedef_Col_double <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Col_double`, x)
}

typedef_Col_int <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Col_int`, x)
}

typedef_uvec <- function(x) {
  .Call(`_cpp11armadillotest_typedef_uvec`, x)
}

typedef_Mat_double <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Mat_double`, x)
}

typedef_Mat_int <- function(x) {
  .Call(`_cpp11armadillotest_typedef_Mat_int`, x)
}

typedef_SpMat_double <- function(x) {
  .Call(`_cpp11armadillotest_typedef_SpMat_double`, x)
}

typedef_SpMat_int <- function(x) {
  .Call(`_cpp11armadillotest_typedef_SpMat_int`, x)
}

random_matrix_nxn <- function(n) {
  .Call(`_cpp11armadillotest_random_matrix_nxn`, n)
}

matrix_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_matrix_fun1_`, a)
}

matrix_fun2_ <- function(a) {
  .Call(`_cpp11armadillotest_matrix_fun2_`, a)
}

column_fun1_ <- function(x, y) {
  .Call(`_cpp11armadillotest_column_fun1_`, x, y)
}

row_fun1_ <- function(x, y) {
  .Call(`_cpp11armadillotest_row_fun1_`, x, y)
}

cube_fun1_ <- function(a, b) {
  .Call(`_cpp11armadillotest_cube_fun1_`, a, b)
}

field_fun1_ <- function(a, b) {
  .Call(`_cpp11armadillotest_field_fun1_`, a, b)
}

attr_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_attr_fun1_`, a)
}

access_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_access_fun1_`, a)
}

initialization_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_initialization_fun1_`, a)
}

zeros_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_zeros_fun1_`, a)
}

ones_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_ones_fun1_`, a)
}

eye_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_eye_fun1_`, a)
}

randu_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_randu_fun1_`, a)
}

randn_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_randn_fun1_`, a)
}

randu_fun2_ <- function(n) {
  .Call(`_cpp11armadillotest_randu_fun2_`, n)
}

randn_fun2_ <- function(n) {
  .Call(`_cpp11armadillotest_randn_fun2_`, n)
}

fill_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_fill_fun1_`, a)
}

imbue_fun1_ <- function(a) {
  .Call(`_cpp11armadillotest_imbue_fun1_`, a)
}

imbue_fun2_ <- function(a) {
  .Call(`_cpp11armadillotest_imbue_fun2_`, a)
}

clean_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_clean_fun1_`, n)
}

replace_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_replace_fun1_`, n)
}

clamp_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_clamp_fun1_`, n)
}

transform_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_transform_fun1_`, n)
}

for_each_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_for_each_fun1_`, n)
}

set_size_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_set_size_fun1_`, n)
}

reshape_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_reshape_fun1_`, n)
}

resize_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_resize_fun1_`, n)
}

copy_size_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_copy_size_fun1_`, n)
}

reset_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_reset_fun1_`, n)
}

subview_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_subview_fun1_`, n)
}

subview_fun2_ <- function(n) {
  .Call(`_cpp11armadillotest_subview_fun2_`, n)
}

diagonal_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_diagonal_fun1_`, n)
}

each_col_fun1_ <- function(n) {
  .Call(`_cpp11armadillotest_each_col_fun1_`, n)
}
