# Generated by cpp11: do not edit by hand

eigen_sym_mat <- function(x) {
  .Call(`_armadillotest_eigen_sym_mat`, x)
}

eigen_sym_dbl <- function(x) {
  .Call(`_armadillotest_eigen_sym_dbl`, x)
}

eigen_gen_mat <- function(x) {
  .Call(`_armadillotest_eigen_gen_mat`, x)
}

eigen_gen_mat_complex_wrapper <- function(x) {
  .Call(`_armadillotest_eigen_gen_mat_complex_wrapper`, x)
}

eigen_gen_dbl <- function(x) {
  .Call(`_armadillotest_eigen_gen_dbl`, x)
}

eigen_gen_dbl_complex_wrapper <- function(x) {
  .Call(`_armadillotest_eigen_gen_dbl_complex_wrapper`, x)
}

eigen_gen_dbl_2 <- function(x) {
  .Call(`_armadillotest_eigen_gen_dbl_2`, x)
}

eigen_gen_mat_complex_wrapper_2 <- function(x) {
  .Call(`_armadillotest_eigen_gen_mat_complex_wrapper_2`, x)
}

ols_mat <- function(y, x) {
  .Call(`_armadillotest_ols_mat`, y, x)
}

ols_dbl <- function(y, x) {
  .Call(`_armadillotest_ols_dbl`, y, x)
}

ols_dbl2 <- function(y, x) {
  .Call(`_armadillotest_ols_dbl2`, y, x)
}

ols_dbl3 <- function(y, x) {
  .Call(`_armadillotest_ols_dbl3`, y, x)
}

capm <- function(r, m, f) {
  .Call(`_armadillotest_capm`, r, m, f)
}

chol_mat <- function(x, type) {
  .Call(`_armadillotest_chol_mat`, x, type)
}

qr_mat <- function(x, econ) {
  .Call(`_armadillotest_qr_mat`, x, econ)
}

typedef_Col_double <- function(x) {
  .Call(`_armadillotest_typedef_Col_double`, x)
}

typedef_Col_int <- function(x) {
  .Call(`_armadillotest_typedef_Col_int`, x)
}

typedef_uvec <- function(x) {
  .Call(`_armadillotest_typedef_uvec`, x)
}

typedef_Mat_double <- function(x) {
  .Call(`_armadillotest_typedef_Mat_double`, x)
}

typedef_Mat_int <- function(x) {
  .Call(`_armadillotest_typedef_Mat_int`, x)
}

typedef_SpMat_double <- function(x) {
  .Call(`_armadillotest_typedef_SpMat_double`, x)
}

typedef_SpMat_int <- function(x) {
  .Call(`_armadillotest_typedef_SpMat_int`, x)
}
