// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// 01_balassa.cpp
doubles_matrix<> balassa_arma_(const doubles_matrix<>& x);
extern "C" SEXP _balassacpp11armadillo_balassa_arma_(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(balassa_arma_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_balassacpp11armadillo_balassa_arma_", (DL_FUNC) &_balassacpp11armadillo_balassa_arma_, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_balassacpp11armadillo(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
