// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// demo.cpp
doubles_matrix<> transpose_(const doubles_matrix<>& x);
extern "C" SEXP _mypackage_transpose_(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(transpose_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_mypackage_transpose_", (DL_FUNC) &_mypackage_transpose_, 1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_mypackage(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
