# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit cpp11armadillo.rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(ggplot2)

