// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <RcppArmadillo.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>& Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// balassa_arma_
NumericMatrix balassa_arma_(const NumericMatrix& x);
RcppExport SEXP _balassarcpparmadillo_balassa_arma_(SEXP xSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<const NumericMatrix&>::type x(xSEXP);
  rcpp_result_gen = Rcpp::wrap(balassa_arma_(x));
  return rcpp_result_gen;
  END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_balassarcpparmadillo_balassa_arma_", (DL_FUNC)&_balassarcpparmadillo_balassa_arma_,
     1},
    {NULL, NULL, 0}};

RcppExport void R_init_balassarcpparmadillo(DllInfo* dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
