# R-hub's generic GitHub Actions workflow file with custom test integration
# Adapted to properly run cpp11armadillotest tests on specific containers

name: R-hub Enhanced
run-name: "${{ github.event.inputs.id || 'R-hub check' }}: ${{ github.event.inputs.name || format('Running tests - {0}', github.event.head_commit.message || github.event.pull_request.title || 'triggered by ' + github.triggering_actor) }}"

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Container configurations'
        type: string
        default: 'm1-san,clang-asan,clang-ubsan,valgrind'
      name:
        description: 'Custom run name'
        type: string
      id:
        description: 'Custom run ID'
        type: string
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions: read-all

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      containers: ${{ steps.rhub-setup.outputs.containers }}
      platforms: ${{ steps.rhub-setup.outputs.platforms }}
      should-run: ${{ steps.check-conditions.outputs.should-run }}

    steps:
    - name: Check conditions
      id: check-conditions
      run: |
        # Always run unless explicitly skipped
        echo "should-run=true" >> $GITHUB_OUTPUT
        
    - uses: r-hub/actions/setup@v1
      with:
        config: ${{ github.event.inputs.config }}
      id: rhub-setup
      
    - name: Debug setup outputs
      run: |
        echo "Containers: ${{ steps.rhub-setup.outputs.containers }}"
        echo "Platforms: ${{ steps.rhub-setup.outputs.platforms }}"
        echo "Should run: ${{ steps.check-conditions.outputs.should-run }}"

  linux-containers:
    needs: setup
    if: ${{ needs.setup.outputs.should-run == 'true' && needs.setup.outputs.containers != '[]' && needs.setup.outputs.containers != '' }}
    runs-on: ubuntu-latest
    name: "Linux: ${{ matrix.config.label || matrix.config.container || 'Container check' }}"
    
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.containers) }}
        
    container:
      image: ${{ matrix.config.container }}
      options: --user root
      
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: r-hub/actions/checkout@v1
      
      - name: Debug configuration
        run: |
          echo "Running with config: ${{ toJson(matrix.config) }}"
          echo "Container: ${{ matrix.config.container }}"
          echo "Event: ${{ github.event_name }}"
          
      - uses: r-hub/actions/platform-info@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
          
      - uses: r-hub/actions/setup-deps@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
          
      - name: Install additional dependencies
        run: |
          # Ensure pak is available
          if (!requireNamespace("pak", quietly = TRUE)) {
            install.packages("pak", repos = "https://r-lib.github.io/p/pak/devel/")
          }
        shell: Rscript {0}
        
      - name: Install main package
        run: |
          options(warn = 2)
          pak::local_install(".", dependencies = TRUE, upgrade = TRUE)
        shell: Rscript {0}
        
      - name: Install cpp11armadillotest
        run: |
          options(warn = 2)
          # Install cpp11armadillotest with tests
          if (dir.exists("cpp11armadillotest")) {
            pak::local_install("cpp11armadillotest", dependencies = TRUE, upgrade = TRUE)
            install.packages("cpp11armadillotest", repos = NULL, INSTALL_opts = "--install-tests", type = "source")
          } else {
            cat("cpp11armadillotest directory not found, skipping installation\n")
          }
        shell: Rscript {0}
        
      - uses: r-hub/actions/run-check@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
          
      - name: Run cpp11armadillotest tests
        run: |
          if (dir.exists("cpp11armadillotest/tests")) {
            setwd("cpp11armadillotest/tests")
            library(testthat)
            if (requireNamespace("cpp11armadillotest", quietly = TRUE)) {
              library(cpp11armadillotest)
              test_check("cpp11armadillotest", reporter = "progress")
            } else {
              cat("cpp11armadillotest package not available, skipping tests\n")
            }
          } else {
            cat("cpp11armadillotest/tests directory not found, skipping tests\n")
          }
        shell: Rscript {0}
        continue-on-error: false

  other-platforms:
    needs: setup
    if: ${{ needs.setup.outputs.should-run == 'true' && needs.setup.outputs.platforms != '[]' && needs.setup.outputs.platforms != '' }}
    runs-on: ${{ matrix.config.os }}
    name: "Platform: ${{ matrix.config.label || matrix.config.os || 'Other platform' }}"
    
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.setup.outputs.platforms) }}
        
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: r-hub/actions/checkout@v1
      
      - name: Debug configuration
        run: |
          echo "Running with config: ${{ toJson(matrix.config) }}"
          echo "OS: ${{ matrix.config.os }}"
          echo "Event: ${{ github.event_name }}"
          
      - uses: r-hub/actions/setup-r@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
          
      - uses: r-hub/actions/platform-info@v1
        with:
          token: ${{ secrets.RHUB_TOKEN }}
          job-config: ${{ matrix.config.job-config }}
          
      - uses: r-hub/actions/setup-deps@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
          
      - name: Install additional dependencies
        run: |
          if (!requireNamespace("pak", quietly = TRUE)) {
            install.packages("pak", repos = "https://r-lib.github.io/p/pak/devel/")
          }
        shell: Rscript {0}
        
      - name: Install main package
        run: |
          options(warn = 2)
          pak::local_install(".", dependencies = TRUE, upgrade = TRUE)
        shell: Rscript {0}
        
      - name: Install cpp11armadillotest
        run: |
          options(warn = 2)
          if (dir.exists("cpp11armadillotest")) {
            pak::local_install("cpp11armadillotest", dependencies = TRUE, upgrade = TRUE)
            install.packages("cpp11armadillotest", repos = NULL, INSTALL_opts = "--install-tests", type = "source")
          } else {
            cat("cpp11armadillotest directory not found, skipping installation\n")
          }
        shell: Rscript {0}
        
      - uses: r-hub/actions/run-check@v1
        with:
          job-config: ${{ matrix.config.job-config }}
          token: ${{ secrets.RHUB_TOKEN }}
          
      - name: Run cpp11armadillotest tests
        run: |
          if (dir.exists("cpp11armadillotest/tests")) {
            setwd("cpp11armadillotest/tests")
            library(testthat)
            if (requireNamespace("cpp11armadillotest", quietly = TRUE)) {
              library(cpp11armadillotest)
              test_check("cpp11armadillotest", reporter = "progress")
            } else {
              cat("cpp11armadillotest package not available, skipping tests\n")
            }
          } else {
            cat("cpp11armadillotest/tests directory not found, skipping tests\n")
          }
        shell: Rscript {0}
        continue-on-error: false
        