# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'release', custom: 'no-cpp11armadillotest'}
          - {os: ubuntu-latest,   r: 'release', custom: 'cpp15'} # CRAN email Dec 7, 2024

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install cpp11armadillotest
        if: matrix.config.custom != 'no-cpp11armadillotest'
        run: |
          options(warn = 2)
          pak::local_install_dev_deps("cpp11armadillotest", dependencies = TRUE)
          install.packages(".", repos = NULL, type = "source")
          install.packages("cpp11armadillotest", repos = NULL, INSTALL_opts = "--install-tests", type = "source")
        shell: Rscript {0}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

      - name: Run cpp11armadillotest tests
        if: matrix.config.custom != 'no-cpp11armadillotest'
        run: |
          setwd("cpp11armadillotest/tests")
          library(testthat)
          library(cpp11armadillotest)
          test_check("cpp11armadillotest", reporter = "progress")
        shell: Rscript {0}

  test-cpp15:
    runs-on: ubuntu-latest

    name: Test with C++15

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - name: Install pandoc-citeproc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc-citeproc

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - name: Install package with C++15
        run: |
          options(warn = 2)
          Sys.setenv(CXXFLAGS = "-std=c++15")
          install.packages(".", repos = NULL, type = "source")
        shell: Rscript {0}

      - name: Check package
        run: |
          options(warn = 2)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "error")
        shell: Rscript {0}
        