# Generated by cpp11: do not edit by hand

ols_mat_ <- function(y, x) {
  .Call(`_econometrics_ols_mat_`, y, x)
}

influence_dbl_ <- function(y, x) {
  .Call(`_econometrics_influence_dbl_`, y, x)
}

stderr_dbl_ <- function(y, x) {
  .Call(`_econometrics_stderr_dbl_`, y, x)
}

beta_stderr_dbl_ <- function(y, x) {
  .Call(`_econometrics_beta_stderr_dbl_`, y, x)
}

ddk_dbl_ <- function(y, x, z) {
  .Call(`_econometrics_ddk_dbl_`, y, x, z)
}
