# Generated by cpp11: do not edit by hand

ols_mat_ <- function(y, x) {
  .Call(`_econometrics_ols_mat_`, y, x)
}

influence_dbl_ <- function(y, x) {
  .Call(`_econometrics_influence_dbl_`, y, x)
}

ols2_mat_ <- function(y, x) {
  .Call(`_econometrics_ols2_mat_`, y, x)
}

cls_mat_ <- function(y, x) {
  .Call(`_econometrics_cls_mat_`, y, x)
}

ddk_mat_ <- function(y, x, z) {
  .Call(`_econometrics_ddk_mat_`, y, x, z)
}

ols3_mat_ <- function(y, x) {
  .Call(`_econometrics_ols3_mat_`, y, x)
}

cns_mat_ <- function(y, x, r) {
  .Call(`_econometrics_cns_mat_`, y, x, r)
}

emd_mat_ <- function(y, x, r) {
  .Call(`_econometrics_emd_mat_`, y, x, r)
}
